php /home/rad/rpm/build.php admin.ds -f
php /home/rad/rpm/build.php api.ds -f
php /home/rad/rpm/build.php rad -f
php /home/rad/rpm/build.php api.rad -f
php /home/rad/rpm/build.php track.rad -f
php /home/rad/rpm/build.php bounce.rad -f
php /home/rad/rpm/build.php cli.rad -f
php /home/rad/rpm/build.php mydns.rad -f
php /home/rad/rpm/build.php test.rad -f
php /home/rad/rpm/build.php gre.rad -f